name: deploy_site

on:
  push:
    branches:
      - automated

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: staging
        run: |
          mkdir -p staging
          rsync -av --exclude='staging' --exclude='README*' --exclude='.git*' * staging
        shell: bash
      - name: upload_s3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "staging"
          destination_dir: ""
